---
title: Vector - A technical Festival
timezone: UTC
collections:
  posts:
    title: Posts
    output: true
  uploads:
    title: Uploads
    output: true
email: mail@amritghimire.com
description: VECTOR – Direct your Vision is a national level technical festival of
  Paschimanchal Campus organized by Free Students Union, Paschimanchal Campus in association
  with different active Technical Clubs from Paschimanchal Campus. In this festival,
  different Project exhibition, Project Competition, Code Camp, Code with Coffee  and
  Mapathon are held along with real time competitions such as Coding Contest and Circuit
  designing. This festival provides practical knowledge and competitive spirits to
  the students of technical field. This festival aims to develop potential of students
  and also improve the technical sectors all over Nepal. This festival inspires and
  helps to direct the solutions and ideas developed to be implemented in real life.
baseurl: ''
url: ''
twitter_username: vectorfsu2018
github_username: jekyll
facebook_username: vectorfsu2018
date: 3 rd ,4 th & 5 th Shrawan, 2075
markdown: kramdown
theme: minima
plugins:
- jekyll-feed
